import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getDatabase, ref, set, update, onValue, push, serverTimestamp, runTransaction, get } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
import { Chess } from "https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm";

const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const db = getDatabase(app, "https://d2t-catur-online-default-rtdb.asia-southeast1.firebasedatabase.app");
const $ = id => document.getElementById(id);
const FILES = ["a","b","c","d","e","f","g","h"];
const PIECES = { p:"♟", n:"♞", b:"♝", r:"♜", q:"♛", k:"♚", P:"♙", N:"♘", B:"♗", R:"♖", Q:"♕", K:"♔" };
const START_FEN = new Chess().fen();
const START_TIME = 600;

let roomId=null,myColor=null,myName="",myUid=null,selected=null,localChess=new Chess(),gameData=null,roomUnsub=null,chatUnsub=null,clockTimer=null,solo=false,soloEnded=false,aiBusy=false,soloInputLock=false,computerTimer=null,computerColor="b",humanColor="w",computerLevel="normal",soloWhiteTime=START_TIME,soloBlackTime=START_TIME,soloTurnStarted=0,pageLeaving=false,timeoutClaiming=false;
const colorName=c=>c==="w"?"Putih":"Hitam";
const levelName=x=>({easy:"Easy",normal:"Normal",professional:"Professional",world:"World Class"}[x]||x);
const formatTime=n=>{n=Math.max(0,Math.ceil(Number(n)||0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`};
const cleanName=v=>String(v||"").trim().replace(/[<>]/g,"").slice(0,20);
const makeRoomCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
function setLobbyMsg(t){const e=$("lobbyMsg");if(e)e.textContent=t||""}
function setGameMsg(t){const e=$("gameMsg");if(e)e.textContent=t||""}
function roomRef(id=roomId){return ref(db,`rooms/${id}`)}
function enterGame(){$("lobby")?.classList.add("hidden");$("game")?.classList.remove("hidden");selected=null}
function stopEverything(){if(roomUnsub)roomUnsub();if(chatUnsub)chatUnsub();roomUnsub=null;chatUnsub=null;clearInterval(clockTimer);clockTimer=null;clearTimeout(computerTimer);computerTimer=null;selected=null;aiBusy=false;soloInputLock=false;timeoutClaiming=false}
function account(){return window.chessAccount?.getUser?.()||null}
function announceGame(mode,id){window.chessAccount?.setGame?.(id,mode)}

onValue(ref(db,".info/connected"),snap=>{const e=$("connection");if(!e)return;const online=snap.val()===true;e.textContent=online?"● Online":"● Menghubungkan...";e.className=online?"status online":"status offline"});
document.querySelectorAll('input[name="gameMode"]').forEach(r=>r.addEventListener("change",()=>{const c=r.value==="computer";$("computerSettings")?.classList.toggle("hidden",!c);$("onlineSettings")?.classList.toggle("hidden",c);setLobbyMsg("")}));

async function createRoom(){if(pageLeaving)return;try{const a=account();if(!a){setLobbyMsg("🔐 Silakan Login / Daftar terlebih dahulu untuk bermain Online.");$("accountModal")?.classList.remove("hidden");return}stopEverything();solo=false;pageLeaving=false;myUid=a.uid;myName=cleanName($("playerName")?.value||a.displayName||"Pemain")||"Pemain";let code="";for(let i=0;i<8;i++){const c=makeRoomCode();const s=await get(roomRef(c));if(!s.exists()){code=c;break}}if(!code)throw Error("Tidak dapat membuat kode room unik. Coba lagi.");roomId=code;myColor="w";await set(roomRef(),{createdAt:serverTimestamp(),status:"waiting",fen:START_FEN,turn:"w",whiteUid:myUid,blackUid:"",whiteName:myName,blackName:"",whiteTime:START_TIME,blackTime:START_TIME,lastTick:Date.now(),winner:"",lastMove:"",lastMoveAt:0,drawOffer:"",moves:{}});$("roomInput").value=roomId;enterGame();$("roomTitle").textContent=`ROOM ${roomId}`;$("roleText").textContent="Anda: Putih";$("roomInfo").textContent=roomId;$("roomStatus").textContent="waiting";announceGame("online",roomId);listenRoom();listenChat()}catch(e){console.error(e);roomId=null;setLobbyMsg(`Gagal membuat room: ${e?.message||"kesalahan tidak diketahui"}`)}}

async function joinRoom(){if(pageLeaving)return;try{const a=account();if(!a){setLobbyMsg("🔐 Silakan Login / Daftar terlebih dahulu untuk bermain Online.");$("accountModal")?.classList.remove("hidden");return}const code=String($("roomInput")?.value||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8);if(code.length<4){setLobbyMsg("Masukkan kode room yang benar.");return}stopEverything();solo=false;pageLeaving=false;myUid=a.uid;myName=cleanName($("playerName")?.value||a.displayName||"Pemain")||"Pemain";roomId=code;myColor=null;setLobbyMsg(`🔎 Mencari ROOM ${code}...`);
const snap=await get(roomRef(code));if(!snap.exists()){roomId=null;setLobbyMsg(`❌ ROOM ${code} tidak ditemukan. Pastikan pemain pertama masih berada di room dan kode sama persis.`);return}const d=snap.val()||{};if(String(d.whiteUid||"")===String(myUid)){roomId=null;setLobbyMsg("❌ Anda sudah menjadi pemilik room ini. Buka room di perangkat/browser lain untuk pemain kedua.");return}if(d.status!=="waiting"){roomId=null;setLobbyMsg("❌ ROOM sudah penuh atau permainan sudah dimulai.");return}if(d.blackUid){roomId=null;setLobbyMsg("❌ ROOM sudah memiliki pemain kedua.");return}
setLobbyMsg("🔄 Menghubungkan Anda sebagai pemain Hitam...");
const tx=await runTransaction(roomRef(code),cur=>{if(!cur)return;if(cur.status!=="waiting"||cur.blackUid)return;return {...cur,blackUid:myUid,blackName:myName,status:"playing",lastTick:Date.now()}});
if(!tx.committed){const latest=tx.snapshot?.val?.()||{};roomId=null;if(!tx.snapshot?.exists?.())setLobbyMsg(`❌ ROOM ${code} hilang sebelum bergabung.`);else if(latest.blackUid||latest.status!=="waiting")setLobbyMsg("❌ ROOM baru saja diambil pemain lain.");else setLobbyMsg("❌ Gagal bergabung ke ROOM. Coba sekali lagi.");return}
myColor="b";enterGame();$("roomTitle").textContent=`ROOM ${roomId}`;$("roleText").textContent="Anda: Hitam";$("roomInfo").textContent=roomId;$("roomStatus").textContent="playing";setLobbyMsg("");announceGame("online",roomId);listenRoom();listenChat()}catch(e){console.error("joinRoom:",e);roomId=null;const m=String(e?.message||"");if(/permission|denied/i.test(m))setLobbyMsg("❌ Firebase menolak akses. Realtime Database Rules perlu mengizinkan login membaca/menulis rooms.");else if(/network|offline|disconnected/i.test(m))setLobbyMsg("❌ Koneksi Firebase terputus. Tunggu sampai status ● Online lalu coba lagi.");else setLobbyMsg(`❌ Gagal bergabung: ${m||"kesalahan tidak diketahui"}`)}}

function listenRoom(){if(roomUnsub)roomUnsub();roomUnsub=onValue(roomRef(),s=>{if(!s.exists()){gameData=null;setGameMsg("Room sudah tidak tersedia.");return}gameData=s.val();if(!myColor){if(String(gameData.whiteUid||"")===String(myUid))myColor="w";else if(String(gameData.blackUid||"")===String(myUid))myColor="b"}renderOnline()},e=>{console.error("Room listener:",e);setGameMsg("Koneksi room bermasalah. Memuat ulang data...")})}
function remaining(d){let w=Number(d?.whiteTime??START_TIME),b=Number(d?.blackTime??START_TIME);if(d?.status==="playing"){const el=Math.max(0,(Date.now()-Number(d.lastTick||Date.now()))/1000);if(d.turn==="w")w=Math.max(0,w-el);else if(d.turn==="b")b=Math.max(0,b-el)}return{w,b}}
function statusText(d){if(!d)return"";if(d.status==="waiting")return"Menunggu pemain kedua...";if(d.status==="playing")return d.turn===myColor?"🎯 Giliran Anda — hanya Anda yang boleh jalan":"⏳ Giliran lawan";if(d.status==="checkmate")return`♚ Skakmat! ${colorName(d.winner)} menang.`;if(d.status==="stalemate")return"🤝 Remis — Stalemate.";if(d.status==="draw")return"🤝 Remis.";if(d.status==="resigned")return`🏆 ${colorName(d.winner)} menang.`;if(d.status==="timeout")return`⏰ Waktu habis. ${colorName(d.winner)} menang.`;return"Permainan selesai."}
function renderOnline(){if(!gameData||solo)return;$("roomTitle").textContent=`ROOM ${roomId}`;$("roleText").textContent=`Anda: ${colorName(myColor)}`;$("aiBadge")?.classList.add("hidden");$("chatCard")?.classList.remove("hidden");$("copyBtn")?.classList.remove("hidden");$("whiteName").textContent=gameData.whiteName||"Menunggu...";$("blackName").textContent=gameData.blackName||"Menunggu...";$("roomInfo").textContent=roomId||"-";$("roomStatus").textContent=gameData.status||"waiting";const t=remaining(gameData);$("whiteClock").textContent=formatTime(t.w);$("blackClock").textContent=formatTime(t.b);let m=statusText(gameData);if(gameData.status==="playing"&&gameData.drawOffer&&gameData.drawOffer!==myColor)m="🤝 Lawan menawarkan remis — tekan tombol Remis untuk menerima.";setGameMsg(m);renderBoard(gameData.fen||START_FEN,myColor);startOnlineClock()}
function startOnlineClock(){clearInterval(clockTimer);if(!gameData||solo||gameData.status!=="playing")return;clockTimer=setInterval(()=>{if(!gameData||solo||gameData.status!=="playing")return;const t=remaining(gameData);$("whiteClock").textContent=formatTime(t.w);$("blackClock").textContent=formatTime(t.b);if(t.w<=0||t.b<=0)claimTimeout()},250)}
async function claimTimeout(){if(timeoutClaiming||!roomId||!gameData||gameData.status!=="playing")return;timeoutClaiming=true;try{await runTransaction(roomRef(),d=>{if(!d||d.status!=="playing")return;const t=remaining(d);if(t.w>0&&t.b>0)return;return{...d,status:"timeout",winner:t.w<=0?"b":"w",whiteTime:t.w,blackTime:t.b,lastTick:Date.now(),drawOffer:""}})}catch(e){console.error("timeout:",e)}finally{timeoutClaiming=false}}
function renderBoard(fen,orientation="w"){try{localChess=new Chess(fen||START_FEN)}catch{localChess=new Chess()}const board=$("board");if(!board)return;board.innerHTML="";const rows=orientation==="w"?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8],fs=orientation==="w"?FILES:[...FILES].reverse();for(const r of rows)for(const f of fs){const fi=FILES.indexOf(f),sq=`${f}${r}`,p=localChess.get(sq),cell=document.createElement("div");cell.className=`sq ${((fi+r)%2===0)?"light":"dark"}`;cell.dataset.square=sq;if(selected===sq)cell.classList.add("selected");if(selected){try{const mv=localChess.moves({square:selected,verbose:true}).find(x=>x.to===sq);if(mv)cell.classList.add(p?"capture":"legal")}catch{}}if(p){const span=document.createElement("span");span.className=`piece ${p.color==="w"?"piece-white":"piece-black"}`;span.textContent=PIECES[p.color==="w"?p.type.toUpperCase():p.type];cell.appendChild(span)}cell.addEventListener("click",()=>clickSquare(sq));board.appendChild(cell)}}
async function clickSquare(sq){if(solo)return clickSolo(sq);if(!gameData||gameData.status!=="playing"||gameData.turn!==myColor)return;const p=localChess.get(sq);if(!selected){if(p&&p.color===myColor){selected=sq;renderBoard(gameData.fen,myColor)}return}if(sq===selected){selected=null;renderBoard(gameData.fen,myColor);return}const from=selected;selected=null;try{const result=await runTransaction(roomRef(),d=>{if(!d||d.status!=="playing"||d.turn!==myColor)return;const t=remaining(d);if(t.w<=0||t.b<=0)return{...d,status:"timeout",winner:t.w<=0?"b":"w",whiteTime:t.w,blackTime:t.b,lastTick:Date.now()};const c=new Chess(d.fen||START_FEN),piece=c.get(from);if(!piece||piece.color!==myColor)return;let move;try{move=c.move({from,to:sq,promotion:"q"})}catch{return}let status="playing",winner="";if(c.isCheckmate()){status="checkmate";winner=myColor}else if(c.isStalemate())status="stalemate";else if(c.isDraw())status="draw";const moves={...(d.moves||{})};moves[`m_${Date.now()}_${Math.random().toString(36).slice(2,8)}`]={from:move.from,to:move.to,fen:c.fen(),by:myColor,at:Date.now(),san:move.san};return{...d,fen:c.fen(),turn:c.turn(),status,moves,lastMove:move.san,lastMoveAt:Date.now(),lastTick:Date.now(),drawOffer:"",whiteTime:t.w,blackTime:t.b,winner}});if(!result?.committed)renderOnline()}catch(e){console.error("move:",e);renderOnline()}}

/* Solo engine and controls remain compatible with the existing game implementation. */
function startSolo(){stopEverything();solo=true;soloEnded=false;pageLeaving=false;humanColor=$("computerSide")?.value==="b"?"b":"w";computerColor=humanColor==="w"?"b":"w";computerLevel=$("computerLevel")?.value||"normal";myColor=humanColor;const a=account();myUid=a?.uid||null;myName=cleanName($("playerName")?.value||a?.displayName||"Pemain")||"Pemain";localChess=new Chess();roomId=null;soloWhiteTime=START_TIME;soloBlackTime=START_TIME;soloTurnStarted=Date.now();gameData={fen:localChess.fen(),turn:"w",status:"playing",whiteName:humanColor==="w"?myName:"Computer",blackName:humanColor==="b"?myName:"Computer",winner:""};enterGame();$("roomTitle").textContent="VS COMPUTER";$("roleText").textContent=`Anda: ${colorName(humanColor)}`;$("aiBadge")?.classList.remove("hidden");$("chatCard")?.classList.add("hidden");$("copyBtn")?.classList.add("hidden");$("roomInfo").textContent="COMPUTER";$("roomStatus").textContent=levelName(computerLevel);$("aiInfo").textContent=`Level ${levelName(computerLevel)} • 10 menit per pemain • ${humanColor==="w"?"Anda jalan pertama":"Computer jalan pertama"}`;announceGame("computer",`solo_${Date.now()}_${myUid||"guest"}`);renderSolo();startSoloClock();if(computerColor==="w")scheduleAI()}
function soloRemaining(){let w=soloWhiteTime,b=soloBlackTime;if(!soloEnded){const e=Math.max(0,(Date.now()-soloTurnStarted)/1000);if(gameData?.turn==="w")w=Math.max(0,w-e);else if(gameData?.turn==="b")b=Math.max(0,b-e)}return{w,b}}
function startSoloClock(){clearInterval(clockTimer);clockTimer=setInterval(()=>{if(!solo||soloEnded)return;const t=soloRemaining();$("whiteClock").textContent=formatTime(t.w);$("blackClock").textContent=formatTime(t.b);if(t.w<=0||t.b<=0)finishSolo(`⏰ Waktu habis. ${colorName(t.w<=0?"b":"w")} menang.`,t.w<=0?"b":"w","timeout")},200)}
function renderSolo(){if(!gameData)return;const t=soloRemaining();$("whiteName").textContent=gameData.whiteName;$("blackName").textContent=gameData.blackName;$("whiteClock").textContent=formatTime(t.w);$("blackClock").textContent=formatTime(t.b);$("gameMsg").textContent=gameData.status==="playing"?(gameData.turn===humanColor?"🎯 Giliran Anda — pilih bidak dan kotak tujuan":"⏳ Computer berpikir..."):statusText(gameData);renderBoard(gameData.fen,humanColor)}

function finishSolo(message,winner,type="win"){if(soloEnded)return;soloEnded=true;clearInterval(clockTimer);gameData.status=winner?type:"draw";gameData.winner=winner||"";setGameMsg(message);if(winner===humanColor){window.chessAccount?.award?.("win")}else if(type==="draw"){window.chessAccount?.award?.("draw")}else if(winner&&winner!==humanColor){window.chessAccount?.award?.(type==="resign"?"resign":"loss")}$("winTitle").textContent=winner===humanColor?"🏆 Anda Menang!":winner?"🤖 Computer Menang":"🤝 Remis";$("winText").textContent=message;$("winPanel")?.classList.remove("hidden")}
function legalMovesFor(c,color){const out=[];for(const r of[1,2,3,4,5,6,7,8])for(const f of FILES){const s=`${f}${r}`,p=c.get(s);if(!p||p.color!==color)continue;for(const m of c.moves({square:s,verbose:true}))out.push(m)}return out}
function moveScore(m){let s=0;if(m.captured)s+=m.captured==="q"?900:m.captured==="r"?500:m.captured==="b"||m.captured==="n"?300:100;if(m.promotion)s+=800;return s}
function evalBoard(c){let v={p:100,n:320,b:330,r:500,q:900,k:20000},score=0;for(const r of[1,2,3,4,5,6,7,8])for(const f of FILES){const p=c.get(`${f}${r}`);if(p)score+=(p.color==="w"?1:-1)*v[p.type]}return computerColor==="w"?score:-score}
function minimax(c,depth,alpha,beta,maximizing){if(depth<=0||c.isGameOver())return evalBoard(c);const moves=legalMovesFor(c,c.turn());if(!moves.length)return evalBoard(c);let best=maximizing?-Infinity:Infinity;for(const m of moves){c.move({from:m.from,to:m.to,promotion:m.promotion||"q"});const val=minimax(c,depth-1,alpha,beta,!maximizing);c.undo();if(maximizing){best=Math.max(best,val);alpha=Math.max(alpha,val)}else{best=Math.min(best,val);beta=Math.min(beta,val)}if(beta<=alpha)break}return best}
function chooseAIMove(){const c=new Chess(gameData.fen),moves=legalMovesFor(c,computerColor);if(!moves.length)return null;if(computerLevel==="easy")return moves[Math.floor(Math.random()*moves.length)];const depth=computerLevel==="normal"?1:computerLevel==="professional"?2:3;let best=moves[0],bestVal=-Infinity;for(const m of moves){c.move({from:m.from,to:m.to,promotion:m.promotion||"q"});let val=minimax(c,depth-1,-Infinity,Infinity,false);c.undo();val+=moveScore(m);if(val>bestVal){bestVal=val;best=m}}return best}
function scheduleAI(){clearTimeout(computerTimer);computerTimer=setTimeout(makeAIMove,350)}
function makeAIMove(){if(!solo||soloEnded||aiBusy||gameData?.turn!==computerColor)return;aiBusy=true;try{const m=chooseAIMove();if(!m){finishSolo("🤝 Remis.","","draw");return}localChess=new Chess(gameData.fen);const mv=localChess.move({from:m.from,to:m.to,promotion:m.promotion||"q"});gameData.fen=localChess.fen();gameData.turn=localChess.turn();if(localChess.isCheckmate()){finishSolo(`♚ Skakmat! ${colorName(computerColor)} menang.`,computerColor,"win");renderSolo();return}if(localChess.isStalemate()||localChess.isDraw()){finishSolo("🤝 Remis.","","draw");renderSolo();return}soloTurnStarted=Date.now();renderSolo();if(gameData.turn===computerColor)scheduleAI()}catch(e){console.error("AI:",e)}finally{aiBusy=false}}
function clickSolo(sq){if(!solo||soloEnded||aiBusy||gameData.turn!==humanColor)return;const p=localChess.get(sq);if(!selected){if(p&&p.color===humanColor){selected=sq;renderSolo()}return}if(sq===selected){selected=null;renderSolo();return}const from=selected;selected=null;try{const c=new Chess(gameData.fen),m=c.move({from,to:sq,promotion:"q"});gameData.fen=c.fen();gameData.turn=c.turn();if(c.isCheckmate()){finishSolo("♚ Skakmat! Anda menang.",humanColor,"win");renderSolo();return}if(c.isStalemate()||c.isDraw()){finishSolo("🤝 Remis.","","draw");renderSolo();return}soloTurnStarted=Date.now();renderSolo();if(gameData.turn===computerColor)scheduleAI()}catch{renderSolo()}}

async function resign(){if(solo){if(soloEnded)return;finishSolo("🏳 Anda menyerah. Computer menang.",computerColor,"resign");return}if(!roomId||!gameData||gameData.status!=="playing")return;try{await runTransaction(roomRef(),d=>{if(!d||d.status!=="playing")return;return{...d,status:"resigned",winner:myColor==="w"?"b":"w",lastTick:Date.now()}})}catch(e){console.error(e)}}
async function offerDraw(){if(solo){if(!soloEnded){finishSolo("🤝 Remis.","","draw");renderSolo()}return}if(!roomId||!gameData||gameData.status!=="playing")return;try{await runTransaction(roomRef(),d=>{if(!d||d.status!=="playing")return;if(d.drawOffer&&d.drawOffer!==myColor)return{...d,status:"draw",drawOffer:"",lastTick:Date.now()};return{...d,drawOffer:myColor}})}catch(e){console.error(e)}}
async function sendChat(e){e.preventDefault();const a=account(),input=$("chatInput");if(!roomId||!input||!String(input.value||"").trim()||!a)return;try{await push(ref(db,`rooms/${roomId}/chat`),{uid:a.uid,name:myName,text:String(input.value).trim().slice(0,160),at:serverTimestamp()});input.value=""}catch(err){console.error(err)}}
function listenChat(){if(chatUnsub)chatUnsub();if(!roomId)return;chatUnsub=onValue(ref(db,`rooms/${roomId}/chat`),snap=>{const list=$("chatList");if(!list)return;const rows=[];snap.forEach(x=>rows.push(x.val()||{}));rows.slice(-80).forEach(m=>{const d=document.createElement("div");d.className="chat-row";d.textContent=`${m.name||"Pemain"}: ${m.text||""}`;list.appendChild(d)});list.scrollTop=list.scrollHeight},e=>console.error("chat:",e))}
function copyInvite(){if(!roomId)return;const url=`${location.origin}${location.pathname}?room=${encodeURIComponent(roomId)}`;navigator.clipboard?.writeText(url).then(()=>setGameMsg("🔗 Link undangan disalin." )).catch(()=>setGameMsg(`Kode room: ${roomId}`))}
function finishOnline(){if(!gameData)return;const status=gameData.status;if(["checkmate","draw","stalemate","resigned","timeout"].includes(status)){const humanWon=gameData.winner===myColor;if(humanWon)window.chessAccount?.award?.("win");else if(status==="draw"||status==="stalemate")window.chessAccount?.award?.("draw");else window.chessAccount?.award?.(status==="resigned"?"resign":"loss")}}

function bind(){$("createBtn")?.addEventListener("click",createRoom);$("joinBtn")?.addEventListener("click",joinRoom);$("computerBtn")?.addEventListener("click",startSolo);$("resignBtn")?.addEventListener("click",resign);$("drawBtn")?.addEventListener("click",offerDraw);$("chatForm")?.addEventListener("submit",sendChat);$("copyBtn")?.addEventListener("click",copyInvite);$("winClose")?.addEventListener("click",()=>{$("winPanel")?.classList.add("hidden");location.href=location.pathname});$("newBtn")?.addEventListener("click",async()=>{if(pageLeaving)return;const a=account(),active=solo?!soloEnded:!!(gameData&&gameData.status==="playing");if(a&&active){try{await window.chessAccount?.award?.("exit")}catch(e){console.warn("exit score:",e)}}stopEverything();pageLeaving=true;location.href=location.pathname});const params=new URLSearchParams(location.search),invite=params.get("room");if(invite&&$("roomInput"))$("roomInput").value=invite.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8)}

document.addEventListener("DOMContentLoaded",bind);