*{box-sizing:border-box}
body{margin:0;min-height:100vh;font-family:Inter,Arial,sans-serif;color:#321d2d;background:radial-gradient(circle at 20% 0%,#fff 0,#ffe7f2 38%,#f7d6e7 100%)}
button,input
{font:inherit}
button{border:0;border-radius:12px;padding:11px 16px;cursor:pointer;background:#fff;box-shadow:0 5px 18px #00000012}button:hover{transform:translateY(-1px)}
.page{max-width:1200px;margin:auto;padding:24px}
.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}
.brand{font-weight:900;letter-spacing:3px;font-size:28px}
.brand span{color:#ff3f9c}
.sub,.muted{color:#76586b}
.status{font-size:13px}
.status.online{color:#16834a}
.status.offline{color:#a53d65}
.panel,.card,.board-panel{background:#ffffffc9;border:1px solid #ffffffdd;backdrop-filter:blur(16px);border-radius:26px;box-shadow:0 18px 55px #7e31551c}.lobby{max-width:720px;margin:8vh auto;padding:35px}.lobby h1{font-size:34px;margin:0 0 8px}.lobby label{display:block;margin:25px 0 12px;font-weight:700}.lobby input{width:100%;margin-top:8px}.lobby-actions{display:flex;gap:12px;flex-wrap:wrap}.join{display:flex;gap:8px;flex:1}.join input{margin:0;text-transform:uppercase}.primary{background:linear-gradient(135deg,#ff3f9c,#d4af37);color:white}.notice{margin-top:22px;padding:12px;border-radius:14px;background:#fff3f8;color:#7a5367;font-size:12px}.msg{margin-top:12px;color:#b12b68}input{border:1px solid #ead5e0;background:#fff;padding:12px 14px;border-radius:12px;outline:none}input:focus{border-color:#ff5eaa;box-shadow:0 0 0 3px #ff5eaa18}.game{display:grid;grid-template-columns:minmax(420px,760px) 330px;gap:20px}.hidden{display:none}.board-panel{padding:18px}.gamebar{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.gamebar span{display:block;color:#8a6476;font-size:12px;margin-top:3px}.board{width:min(100%,700px);aspect-ratio:1;margin:auto;display:grid;grid-template-columns:repeat(8,1fr);border:8px solid #4b2639;border-radius:14px;overflow:hidden;box-shadow:0 12px 35px #2d102030}.sq{position:relative;display:flex;align-items:center;justify-content:center;font-size:clamp(28px,6vw,58px);user-select:none;cursor:pointer}.sq.light{background:#f7dfd0}.sq.dark{background:#a95c75}.sq.selected{outline:"fim_middle" solid 4px #ff3f9c;outline-offset:-4px}.sq.last-move{background:#ff3f9c2e}.sq.check{background:#ff3f9c5e}.sq .piece{pointer-events:none}.board-panel h2{margin:0 0 12px;font-size:20px}.board-panel .player{display:flex;align-items:center;gap:12px;margin-bottom:12px}.board-panel .player .status{font-size:11px;margin-top:0}.board-panel .player .name{font-weight:700}.board-panel .player .score{margin-left:auto;font-weight:700;color:#8a6476}.board-panel .player.white .name{color:#d4af37}.board-panel .player.black .name{color:#ff3f9c}.board-panel button{width:100%;margin-top:12px}
