import { initializeApp,getApps,getApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getDatabase,ref,set,update,onValue,push,serverTimestamp,runTransaction } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
import { Chess } from "https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm";

const app=getApps().length?getApp():initializeApp(firebaseConfig);
const db=getDatabase(app,"https://d2t-catur-online-default-rtdb.asia-southeast1.firebasedatabase.app");
const $=id=>document.getElementById(id);
const files=["a","b","c","d","e","f","g","h"];
const PIECES={p:"♟",n:"♞",b:"♝",r:"♜",q:"♛",k:"♚",P:"♙",N:"♘",B:"♗",R:"♖",Q:"♕",K:"♔"};
let roomId=null,myColor=null,myName="",selected=null,localChess=new Chess(),gameData=null;
let roomUnsub=null,chatUnsub=null,clockTimer=null,solo=false,soloEnded=false,aiBusy=false,soloInputLock=false,computerTimer=null;
let computerColor="b",humanColor="w",computerLevel="normal",soloWhiteTime=600,soloBlackTime=600,soloTurnStarted=0;
function el(id){return $(id)}
function colorName(c){return c==="w"?"Putih":"Hitam"}
function levelName(x){return({easy:"Easy",normal:"Normal",professional:"Professional",world:"World Class"}[x]||x)}
function formatTime(n){n=Math.max(0,Math.ceil(Number(n)||0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
function enterGame(){el("lobby")?.classList.add("hidden");el("game")?.classList.remove("hidden");selected=null}
function stopEverything(){if(roomUnsub)roomUnsub();if(chatUnsub)chatUnsub();clearInterval(clockTimer);if(computerTimer)clearTimeout(computerTimer);roomUnsub=chatUnsub=clockTimer=computerTimer=null;selected=null;aiBusy=false;soloInputLock=false}
function roomRef(){return ref(db,`rooms/${roomId}`)}
function makeRoomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function validConfig(){return !!(firebaseConfig&&firebaseConfig.apiKey&&!String(firebaseConfig.apiKey).startsWith("TEMPEL"))}

onValue(ref(db,".info/connected"),s=>{const x=el("connection");if(!x)return;if(s.val()){x.textContent="● Online";x.className="status online"}else{x.textContent="● Menghubungkan...";x.className="status offline"}});
document.querySelectorAll('input[name="gameMode"]').forEach(r=>r.addEventListener("change",()=>{const c=r.value==="computer";el("computerSettings")?.classList.toggle("hidden",!c);el("onlineSettings")?.classList.toggle("hidden",c);el("lobbyMsg")&&(el("lobbyMsg").textContent="")}));

async function createRoom(){try{stopEverything();solo=false;myName=(el("playerName")?.value.trim()||`Pemain ${Math.floor(Math.random()*9999)}`).slice(0,20);roomId=makeRoomCode();myColor="w";await set(roomRef(),{createdAt:serverTimestamp(),status:"waiting",fen:new Chess().fen(),turn:"w",whiteName:myName,blackName:"",whiteTime:600,blackTime:600,lastTick:Date.now(),winner:"",lastMove:"",drawOffer:"",moves:{}});el("roomInput").value=roomId;enterGame();el("roomTitle").textContent=`ROOM ${roomId}`;el("roleText").textContent="Anda: Putih";el("roomInfo").textContent=roomId;el("roomStatus").textContent="Menunggu pemain...";listenRoom();listenChat()}catch(e){console.error(e);el("lobbyMsg").textContent="Gagal membuat room: "+e.message}}
async function joinRoom(){try{stopEverything();solo=false;const code=el("roomInput")?.value.trim().toUpperCase();if(!code)return el("lobbyMsg").textContent="Masukkan kode room.";myName=(el("playerName")?.value.trim()||`Pemain ${Math.floor(Math.random()*9999)}`).slice(0,20);roomId=code;const snap=await new Promise(resolve=>onValue(roomRef(),resolve,{onlyOnce:true}));if(!snap.exists())return el("lobbyMsg").textContent="Room tidak ditemukan.";const d=snap.val();if(d.blackName)return el("lobbyMsg").textContent="Room sudah penuh.";myColor="b";await update(roomRef(),{blackName:myName,status:"playing",lastTick:Date.now()});enterGame();listenRoom();listenChat()}catch(e){console.error(e);el("lobbyMsg").textContent="Gagal bergabung: "+e.message}}
function listenRoom(){if(roomUnsub)roomUnsub();roomUnsub=onValue(roomRef(),s=>{if(!s.exists()){el("gameMsg").textContent="Room sudah tidak tersedia.";return}gameData=s.val();renderOnline()})}
function remaining(d){let w=Number(d.whiteTime??600),b=Number(d.blackTime??600);if(d.status==="playing"){const q=Math.max(0,(Date.now()-Number(d.lastTick||Date.now()))/1000);if(d.turn==="w")w=Math.max(0,w-q);else b=Math.max(0,b-q)}return{w,b}}
function renderOnline(){if(!gameData||solo)return;el("roomTitle").textContent=`ROOM ${roomId}`;el("roleText").textContent=`Anda: ${colorName(myColor)}`;el("aiBadge")?.classList.add("hidden");el("chatCard")?.classList.remove("hidden");el("copyBtn")?.classList.remove("hidden");el("whiteName").textContent=gameData.whiteName||"Menunggu...";el("blackName").textContent=gameData.blackName||"Menunggu...";el("roomInfo").textContent=roomId;el("roomStatus").textContent=gameData.status||"Menunggu pemain...";const t=remaining(gameData);el("whiteClock").textContent=formatTime(t.w);el("blackClock").textContent=formatTime(t.b);let m={waiting:"Menunggu pemain kedua...",playing:gameData.turn===myColor?"🎯 Giliran Anda — hanya Anda yang boleh jalan":"⏳ Giliran lawan",checkmate:`♚ Skakmat! ${colorName(gameData.winner)} menang.`,stalemate:"🤝 Remis — Stalemate.",draw:"🤝 Remis.",resigned:`🏆 ${colorName(gameData.winner)} menang.`,timeout:`⏰ Waktu habis. ${colorName(gameData.winner)} menang.`}[gameData.status]||"";if(gameData.status==="playing"&&gameData.drawOffer&&gameData.drawOffer!==myColor)m="🤝 Lawan menawarkan remis — tekan tombol Remis untuk menerima.";el("gameMsg").textContent=m;renderBoard(gameData.fen,myColor);startOnlineClock()}
function startOnlineClock(){clearInterval(clockTimer);clockTimer=setInterval(()=>{if(!gameData||solo||gameData.status!=="playing")return;const t=remaining(gameData);el("whiteClock").textContent=formatTime(t.w);el("blackClock").textContent=formatTime(t.b);if(t.w<=0||t.b<=0)claimTimeout()},250)}
async function claimTimeout(){if(!roomId||!gameData||gameData.status!=="playing")return;try{await runTransaction(roomRef(),d=>{if(!d||d.status!=="playing")return;const t=remaining(d);if(t.w>0&&t.b>0)return;return{...d,status:"timeout",winner:t.w<=0?"b":"w",whiteTime:t.w,blackTime:t.b,lastTick:Date.now()}})}catch(e){console.error(e)}}

function renderBoard(fen,orientation="w"){try{localChess=new Chess(fen)}catch{localChess=new Chess()}const board=el("board");if(!board)return;board.innerHTML="";const rows=orientation==="w"?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];const fs=orientation==="w"?files:[...files].reverse();for(const r of rows)for(const f of fs){const fi=files.indexOf(f),sq=f+r,p=localChess.get(sq),cell=document.createElement("div");cell.className=`sq ${((fi+r)%2===0)?"light":"dark"}`;cell.dataset.square=sq;if(selected===sq)cell.classList.add("selected");if(selected){try{const mv=localChess.moves({square:selected,verbose:true}).find(x=>x.to===sq);if(mv){cell.classList.add("legal");if(p)cell.classList.add("capture")}}catch{}}if(p){const span=document.createElement("span");span.className=`piece ${p.color==="w"?"piece-white":"piece-black"}`;span.textContent=PIECES[p.color==="w"?p.type.toUpperCase():p.type];cell.appendChild(span)}cell.onclick=()=>clickSquare(sq);board.appendChild(cell)}}
async function clickSquare(sq){if(solo)return clickSolo(sq);if(!gameData||gameData.status!=="playing"||gameData.turn!==myColor)return;const p=localChess.get(sq);if(!selected){if(p&&p.color===myColor){selected=sq;renderBoard(gameData.fen,myColor)}return}if(sq===selected){selected=null;renderBoard(gameData.fen,myColor);return}const from=selected;selected=null;try{const result=await runTransaction(roomRef(),d=>{if(!d||d.status!=="playing"||d.turn!==myColor)return;const t=remaining(d);if(t.w<=0||t.b<=0)return{...d,status:"timeout",winner:t.w<=0?"b":"w",whiteTime:t.w,blackTime:t.b,lastTick:Date.now()};const c=new Chess(d.fen),piece=c.get(from);if(!piece||piece.color!==myColor)return;let move;try{move=c.move({from,to:sq,promotion:"q"})}catch{return};let status="playing",winner="";if(c.isCheckmate()){status="checkmate";winner=myColor}else if(c.isStalemate())status="stalemate";else if(c.isDraw())status="draw";const moves={...(d.moves||{})};moves[`m_${Date.now()}_${Math.random().toString(36).slice(2,6)}`]={from:move.from,to:move.to,fen:c.fen(),by:myColor,at:Date.now(),san:move.san};const n={...d,fen:c.fen(),turn:c.turn(),status,moves,lastMove:move.san,lastMoveAt:Date.now(),lastTick:Date.now(),drawOffer:"",whiteTime:t.w,blackTime:t.b};if(winner)n.winner=winner;return n});if(!result.committed)renderOnline()}catch(e){console.error("move",e);renderOnline()}}

function startSolo(){stopEverything();solo=true;soloEnded=false;humanColor=el("computerSide")?.value==="b"?"b":"w";computerColor=humanColor==="w"?"b":"w";computerLevel=el("computerLevel")?.value||"normal";myColor=humanColor;myName=(el("playerName")?.value.trim()||"Pemain").slice(0,20);localChess=new Chess();roomId=null;soloWhiteTime=600;soloBlackTime=600;soloTurnStarted=Date.now();gameData={fen:localChess.fen(),turn:"w",status:"playing",whiteName:humanColor==="w"?myName:"Computer",blackName:humanColor==="b"?myName:"Computer"};enterGame();el("roomTitle").textContent="VS COMPUTER";el("roleText").textContent=`Anda: ${colorName(humanColor)}`;el("aiBadge")?.classList.remove("hidden");el("chatCard")?.classList.add("hidden");el("copyBtn")?.classList.add("hidden");el("roomInfo").textContent="COMPUTER";el("roomStatus").textContent=levelName(computerLevel);el("aiInfo").textContent=`Level ${levelName(computerLevel)} • 10 menit per pemain • ${humanColor==="w"?"Anda jalan pertama":"Computer jalan pertama"}`;renderSolo();startSoloClock();if(computerColor==="w")scheduleAI()}
function soloRemaining(){let w=soloWhiteTime,b=soloBlackTime;if(!soloEnded){const q=Math.max(0,(Date.now()-soloTurnStarted)/1000);if(gameData?.turn==="w")w=Math.max(0,w-q);else b=Math.max(0,b-q)}return{w,b}}
function startSoloClock(){clearInterval(clockTimer);clockTimer=setInterval(()=>{if(!solo||soloEnded)return;const t=soloRemaining();el("whiteClock").textContent=formatTime(t.w);el("blackClock").textContent=formatTime(t.b);if(t.w<=0||t.b<=0){const winner=t.w<=0?"b":"w";finishSolo(`⏰ Waktu habis. ${colorName(winner)} menang.`,winner)}},200)}
function renderSolo(){if(!gameData)return;const t=soloRemaining();el("whiteName").textContent=gameData.whiteName;el("blackName").textContent=gameData.blackName;el("whiteClock").textContent=formatTime(t.w);el("blackClock").textContent=formatTime(t.b);el("gameMsg").textContent=gameData.turn===humanColor?"🎯 Giliran Anda — hanya satu langkah":"⏳ Computer berpikir...";renderBoard(gameData.fen,humanColor)}
function clickSolo(sq){if(soloEnded||soloInputLock||!gameData||gameData.status!=="playing"||gameData.turn!==humanColor)return;const p=localChess.get(sq);if(!selected){if(p&&p.color===humanColor){selected=sq;renderSolo()}return}if(sq===selected){selected=null;renderSolo();return}const from=selected;selected=null;const t=soloRemaining();if((humanColor==="w"?t.w:t.b)<=0)return finishSolo(`⏰ Waktu habis. ${colorName(computerColor)} menang.`,computerColor);const c=new Chess(gameData.fen);let move;try{move=c.move({from,to:sq,promotion:"q"})}catch{renderSolo();return}if(humanColor==="w")soloWhiteTime=t.w;else soloBlackTime=t.b;gameData.fen=c.fen();gameData.turn=c.turn();gameData.status=gameStatus(c,humanColor);gameData.winner=gameData.status==="checkmate"?humanColor:"";soloTurnStarted=Date.now();renderSolo();if(gameData.status!=="playing")return finishFromChess(c,humanColor);soloInputLock=true;scheduleAI()}
function gameStatus(c){if(c.isCheckmate())return"checkmate";if(c.isStalemate()||c.isDraw())return"draw";return"playing"}
function finishFromChess(c,winner){if(c.isCheckmate())finishSolo(`🏆 ${colorName(winner)} menang — Skakmat!`,winner);else finishSolo("🤝 Permainan Remis.","")}
function finishSolo(message,winner=""){if(soloEnded)return;soloEnded=true;clearInterval(clockTimer);if(computerTimer)clearTimeout(computerTimer);computerTimer=null;aiBusy=false;soloInputLock=true;gameData.status=winner?"checkmate":"draw";gameData.winner=winner;el("gameMsg").textContent=message;renderBoard(gameData.fen,humanColor)}
function scheduleAI(){if(soloEnded||aiBusy)return;clearTimeout(computerTimer);const delay={easy:120,normal:500,professional:1200,world:2200}[computerLevel]||500;computerTimer=setTimeout(computerMove,delay)}
function computerMove(){computerTimer=null;if(soloEnded||!solo||!gameData||gameData.turn!==computerColor)return;aiBusy=true;const t=soloRemaining();if((computerColor==="w"?t.w:t.b)<=0){aiBusy=false;return finishSolo(`⏰ Waktu habis. ${colorName(humanColor)} menang.`,humanColor)};const c=new Chess(gameData.fen);const depth={easy:1,normal:2,professional:3,world:3}[computerLevel]||2;const best=chooseMove(c,computerColor,depth);if(!best){aiBusy=false;return finishFromChess(c,humanColor)};let move;try{move=c.move(best)}catch{aiBusy=false;return}if(computerColor==="w")soloWhiteTime=t.w;else soloBlackTime=t.b;gameData.fen=c.fen();gameData.turn=c.turn();gameData.status=gameStatus(c);gameData.winner=gameData.status==="checkmate"?computerColor:"";soloTurnStarted=Date.now();aiBusy=false;soloInputLock=false;renderSolo();if(gameData.status!=="playing")return finishFromChess(c,computerColor)}
function chooseMove(c,color,depth){const moves=c.moves({verbose:true});if(!moves.length)return null;let best=moves[0],bestScore=color==="w"?-Infinity:Infinity;for(const m of moves){c.move(m);const s=minimax(c,depth-1,-Infinity,Infinity,color!=="w");c.undo();if(color==="w"?s>bestScore:s<bestScore){bestScore=s;best=m}}return best}
function minimax(c,depth,alpha,beta,maximizing){if(depth<=0||c.isGameOver())return evaluate(c);const moves=c.moves({verbose:true});if(maximizing){let v=-Infinity;for(const m of moves){c.move(m);v=Math.max(v,minimax(c,depth-1,alpha,beta,false));c.undo();alpha=Math.max(alpha,v);if(beta<=alpha)break}return v}else{let v=Infinity;for(const m of moves){c.move(m);v=Math.min(v,minimax(c,depth-1,alpha,beta,true));c.undo();beta=Math.min(beta,v);if(beta<=alpha)break}return v}}
function evaluate(c){if(c.isCheckmate())return c.turn()==="w"?-100000:100000;if(c.isDraw()||c.isStalemate())return 0;const val={p:100,n:320,b:330,r:500,q:900,k:20000};let score=0;for(const row of c.board())for(const p of row)if(p)score+=(p.color==="w"?1:-1)*val[p.type];return score}

function listenChat(){const list=el("chatList");if(!list||!roomId)return;chatUnsub=onValue(ref(db,`rooms/${roomId}/chat`),s=>{list.innerHTML="";const a=[];s.forEach(c=>a.push(c.val()));a.slice(-80).forEach(m=>{const d=document.createElement("div");d.className="chat-msg";d.textContent=`${m.name||"Pemain"}: ${m.text||""}`;list.appendChild(d)});list.scrollTop=list.scrollHeight})}
async function sendChat(){const input=el("chatInput"),text=input?.value.trim();if(!roomId||!text)return;try{await push(ref(db,`rooms/${roomId}/chat`),{name:myName,text:text.slice(0,160),at:serverTimestamp()});input.value=""}catch(e){console.error(e)}}
async function resign(){if(solo){if(!soloEnded)finishSolo("🏳 Anda menyerah.",computerColor);return}if(!gameData||gameData.status!=="playing")return;try{await update(roomRef(),{status:"resigned",winner:myColor==="w"?"b":"w",lastTick:Date.now()})}catch(e){console.error(e)}}
async function draw(){if(solo){if(confirm("Akhiri permainan dan nyatakan remis?"))finishSolo("🤝 Permainan Remis.","");return}if(!gameData||gameData.status!=="playing")return;const offer=gameData.drawOffer||"";if(offer&&offer!==myColor){if(confirm("Lawan menawarkan remis. Terima?"))await update(roomRef(),{status:"draw",drawOffer:"",lastTick:Date.now()});else await update(roomRef(),{drawOffer:""});return}if(offer===myColor)return;await update(roomRef(),{drawOffer:myColor});el("gameMsg").textContent="🤝 Tawaran remis dikirim. Tunggu jawaban lawan."}
function bind(){el("createBtn")?.addEventListener("click",createRoom);el("joinBtn")?.addEventListener("click",joinRoom);el("computerBtn")?.addEventListener("click",startSolo);el("copyBtn")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(roomId||"");el("gameMsg").textContent="🔗 Kode room disalin."}catch{}});el("resignBtn")?.addEventListener("click",resign);el("drawBtn")?.addEventListener("click",draw);el("newBtn")?.addEventListener("click",()=>{stopEverything();location.href=location.pathname});el("chatForm")?.addEventListener("submit",e=>{e.preventDefault();sendChat()});el("playerName")?.addEventListener("input",e=>localStorage.setItem("chessPlayerName",e.target.value));const saved=localStorage.getItem("chessPlayerName");if(saved&&!el("playerName").value)el("playerName").value=saved}
if(validConfig()){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind()}else{console.error("Firebase config belum benar")}
